# Generated by Django 2.1.4 on 2019-01-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('contact', models.EmailField(blank=True, max_length=300)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('start', models.DateField(null=True, verbose_name='Start date')),
                ('end', models.DateField(null=True, verbose_name='End date')),
                ('accommodation', models.CharField(blank=True, max_length=300, verbose_name='Accomodation address')),
                ('setup', models.DateTimeField(blank=True, null=True, verbose_name='Set up')),
                ('dismantle', models.DateTimeField(blank=True, null=True, verbose_name='Dismantle')),
                ('booth', models.IntegerField(blank=True, default=1, verbose_name='Booth #')),
                ('furniture', models.TextField(blank=True, max_length=300, verbose_name='Furniture provided')),
                ('registrations', models.IntegerField(blank=True, default=1, verbose_name='Complimentary registrations')),
                ('power', models.BooleanField(default=False, verbose_name='Power supplied')),
                ('brochures', models.TextField(blank=True, default='QTY x BROCHURE #', help_text='Include qty', max_length=500, verbose_name='Brochures')),
                ('equipment', models.TextField(blank=True, default='', max_length=500, verbose_name='Equipment')),
                ('banners', models.TextField(blank=True, default='', max_length=200, verbose_name='Banners')),
                ('delivery', models.BooleanField(default=False, verbose_name='Delivered')),
                ('hand', models.BooleanField(default=False, verbose_name='Hand carried')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Delivery address')),
                ('date', models.DateField(blank=True, help_text='2-3 days for Brisbane/Sydney/Adelaide/Melbourne, otherwise 4-5 days', null=True, verbose_name='Ship date')),
                ('details', models.TextField(blank=True, default='', help_text='Artwork required, important links etc.', max_length=400, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Exhibition Summary',
                'verbose_name_plural': 'Exhibition Summaries',
                'ordering': ['-start'],
            },
        ),
    ]
