# Generated by Django 2.1.4 on 2018-12-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0002_auto_20181213_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='date',
            field=models.DateField(help_text='2-3 days for Brisbane/Sydney/Adelaide/Melbourne, otherwise 4-5 days', null=True, verbose_name='Ship date'),
        ),
    ]
