# Generated by Django 2.1.4 on 2018-12-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0003_summary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='accommodation',
            field=models.CharField(blank=True, max_length=300, verbose_name='Accomodation address'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Delivery address'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='banners',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Banners'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='booth',
            field=models.IntegerField(blank=True, verbose_name='Booth #'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='brochures',
            field=models.TextField(blank=True, default='QTY x BROCHURE #', help_text='Include qty', max_length=500, verbose_name='Brochures'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='date',
            field=models.DateField(blank=True, help_text='2-3 days for Brisbane/Sydney/Adelaide/Melbourne, otherwise 4-5 days', null=True, verbose_name='Ship date'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Artwork required, important links etc.', max_length=400, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='equipment',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='furniture',
            field=models.TextField(blank=True, max_length=300, verbose_name='Furniture provided'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='registrations',
            field=models.IntegerField(blank=True, verbose_name='Complimentary registrations'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='venue',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
