# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0004_auto_20181213_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name=b'Delivered'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='hand',
            field=models.BooleanField(default=False, verbose_name=b'Hand carried'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='power',
            field=models.BooleanField(default=False, verbose_name=b'Power supplied'),
        ),
    ]
