# Generated by Django 2.1.4 on 2018-12-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0005_auto_20181213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='booth',
            field=models.IntegerField(blank=True, default=1, verbose_name='Booth #'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='hand',
            field=models.BooleanField(default=False, verbose_name='Hand carried'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='power',
            field=models.BooleanField(default=False, verbose_name='Power supplied'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='registrations',
            field=models.IntegerField(blank=True, default=1, verbose_name='Complimentary registrations'),
        ),
    ]
