# Generated by Django 2.1.4 on 2018-12-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0008_summary_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['start'], 'verbose_name': 'Exhibition Summary', 'verbose_name_plural': 'Exhibition Summaries'},
        ),
    ]
