# Generated by Django 2.1.4 on 2018-12-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0009_auto_20181219_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-start'], 'verbose_name': 'Exhibition Summary', 'verbose_name_plural': 'Exhibition Summaries'},
        ),
        migrations.AddField(
            model_name='summary',
            name='website',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
