# Generated by Django 2.1.4 on 2018-12-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionsummary', '0010_auto_20181220_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='contact',
            field=models.EmailField(blank=True, max_length=300),
        ),
    ]
