# Generated by Django 2.1.4 on 2019-01-08 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('productnumber', models.CharField(help_text='Product # SDXX-XXXX', max_length=9, verbose_name='Product #')),
                ('description', models.TextField(help_text='Enter a description of product', max_length=2000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='applications',
            field=models.ManyToManyField(help_text='Seclect application modalities for this publication', to='products.Solution'),
        ),
        migrations.AddField(
            model_name='publication',
            name='products',
            field=models.ManyToManyField(help_text='Select products used in publication', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.ManyToManyField(help_text='Select application modalities for this product', to='products.Solution'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this product', to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Company'),
        ),
    ]
