# Generated by Django 2.1.4 on 2018-12-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
