# Generated by Django 2.1.4 on 2019-01-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='application',
            new_name='solution',
        ),
    ]
